name = "JpegTurbo"
uuid = "e6522430-9176-47fc-8974-6aa854caea40"
authors = ["Steven G. Johnson <stevenj@alum.mit.edu> and contributors"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
JpegTurbo_jll = "aacddb02-875f-59d6-b918-886e6ef4fbf8"

[compat]
CEnum = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[targets]
test = ["Test", "TestImages"]
